---
title: "Figure 1 Panels a,b,c; Figure S2"
author: "Malte Ruehlemann"
date: "`r Sys.Date()`"
output:
   BiocStyle::html_document:
      toc: true
      df_print: paged
      self_contained: true
      code_download: true
      highlight: tango
#bibliography: mylib.bib
editor_options:
  chunk_output_type: console
params:
  FIGPATH: "figures/"
---

<style type="text/css">
.main-container {
  max-width: 1800px;
  margin-left: auto;
  margin-right: auto;
}
</style>

```{r style}
# Set knit global options
library("knitr")
options(digits = 3, width = 80)
golden_ratio <- (1 + sqrt(5)) / 2
opts_chunk$set(echo = FALSE,
               tidy = FALSE,
               include = TRUE,
               fig.path = params$FIGPATH,
               dev='png',
               fig.height = 7.5,
               fig.width = 6 * golden_ratio,
               warning = F,
               message =F, 
               comment = '  ',
               dpi = 300,
               cache = FALSE)
library("rmarkdown")

# Pretty outputs
library("BiocStyle")
library("ggthemes") # add ggplot2 themes
library("ggplot2")
theme_set(theme_few(base_size = 18))

# Set seed for reproducibility
set.seed(222)
```

```{r}
#setwd("r_analysis_and_plots")
library(ggplot2)
library(tidyverse)
library(ape)
library(ggtree)
library(compositions)
library(phyloseq)
library(picante)
library(ggrepel)
library(reshape2)
library(cowplot)
library(plotly)
library(TreeDist)
library(phytools)
library(parallel)
library(ggpubr)

interactive=F
intermediatedata_folder="~/Desktop/Projects/190712_GreatApes/220303_Analysis_New/intermediate_data/"
setwd("~/Desktop/Projects/190712_GreatApes/220616_dataprocessing/greatapes_mgx_scripts/r_analysis_and_plots//")
load("0_all_preprocessed.Robj")
```




## Abundance differences of genera

```{r}
colset=colset %>% arrange(host_long)
## clr transformation of genus level abundances
gen = gen[!rownames(gen) %in% sample_exclude,]
sgb_abundance = sgb_abundance[!rownames(sgb_abundance) %in% sample_exclude,]
sgb_long = sgb_long %>% filter(!sample %in% sample_exclude)

gen_clr = (gen+1) %>% data.frame %>% clr
gen_clr[gen_clr<0] = 0

### select candidate genera for testing with prevalence > 20% and mean abundance > 0.1% (1000 TPM) in one subgroup 
cand_gen = gen %>% data.frame %>% rownames_to_column("sample") %>% reshape2::melt() %>% left_join(sample_meta) %>% 
  filter(host_genus != "Gorilla") %>% group_by(host_long, variable) %>% 
  summarise(mean_abu = mean(value), mean_prev = mean(value>0)) %>% filter(mean_prev > .2, mean_abu>1000) %>% 
  pull(variable) %>% unique() %>% as.character()

res_gen_file = paste0(intermediatedata_folder, "res_gen.Rds")

if(file.exists(res_gen_file)){
res_gen=readRDS(res_gen_file)
}else{
res_gen = do.call("rbind",lapply(cand_gen, function(cf){
  ab = gen_clr[,cf]
  df = ab %>% reshape2::melt(.) %>% rownames_to_column("sample") %>% left_join(data.frame(gen)[,cf, drop=F] %>% rownames_to_column("sample") %>% select(sample, value_tpm=2)) %>% 
    left_join(sample_meta) %>% filter(host_genus != "Gorilla") %>% mutate(hihdi=host %in% c("HsG","HsD"), human= host %in% c("HsA1","HsG","HsA2","HsD"))
  df_out=data.frame(trait=cf, 
                    comp=c("human","hdi_diff"),
                    summary(lm(value ~ human*hihdi, data = df))$coefficients[2:3,], 
                    bind_rows(df %>% group_by(human) %>% summarize(mean_abu=mean(value)) %>% select(mean_abu) %>% unlist(), 
                              df %>% filter(human) %>% group_by(hihdi) %>% summarize(mean_abu=mean(value)) %>% select(mean_abu) %>% unlist()), 
                    stringsAsFactors = F)
  return(df_out)
})) %>% do.call("bind_rows",.) %>% mutate(log_fold_diff = log((mean_abu2+0.01)/(mean_abu1+0.01)))
saveRDS(res_gen, res_gen_file)
}

res_gen$q <- p.adjust(res_gen$Pr...t..,"bonferroni")
res_gen_sub <- res_gen %>% filter(trait %in% c(res_gen %>% filter(mean_abu1 > 1 | mean_abu2 > 1, q < 0.05) %>% pull(trait))) 

## assign taxa to group
taxa_hihdi = res_gen_sub %>% filter(comp=="hdi_diff", q<0.05, Estimate>0) %>% pull(trait)
taxa_lohdi = res_gen_sub %>% filter(comp=="hdi_diff", q<0.05, Estimate<0) %>% pull(trait)
taxa_human = res_gen_sub %>% filter(comp=="human", q<0.05, Estimate>0) %>% pull(trait)
taxa_pan = res_gen_sub %>% filter(comp=="human", q<0.05, Estimate<0) %>% pull(trait)

res_gen = res_gen %>% mutate(status=case_when(trait %in% taxa_pan ~ "Pan", trait %in% taxa_hihdi ~ "Human_EUR", trait %in% taxa_lohdi ~ "Human_AFR", trait %in% taxa_human ~ "Human", TRUE ~ "other")) 

write.table(res_gen, "figures_and_tables/Suppl_Table_S5_Results_Tax.tsv", row.names = F, sep="\t")

####
```

### Figure 2

```{r}
top_trait_tax = res_gen %>% filter(q<0.05) %>% mutate(dir=sign(t.value)) %>% group_by(comp, dir) %>% slice_min(order_by=q, n=3) %>% pull(trait)
tax_thresh = res_gen %>% arrange(q) %>% filter(q<0.05) %>% tail(1) %>% pull(t.value) %>% abs

fig2_panel_a=res_gen %>% reshape2::dcast(trait ~ comp, value.var="t.value") %>% left_join(res_gen %>% filter(comp=="human") %>% select(trait, log_fold_diff, q)) %>% 
  left_join(sgb_reps %>% mutate(genus2=gsub("[-]",".",genus)) %>% select(trait=genus2, phylum2) %>% distinct()) %>% 
  mutate(status=case_when(trait %in% taxa_pan ~ "Pan", trait %in% taxa_hihdi ~ "Human_EUR", trait %in% taxa_lohdi ~ "Human_AFR", trait %in% taxa_human ~ "Human", TRUE ~ "other")) %>% 
  ggplot(aes(x=human, y=hdi_diff)) + geom_point(aes(col=status, size=abs(log_fold_diff)))  + 
    scale_color_manual(values=c("blue","lightblue3","darkblue","grey","#FF8C00")) + theme(legend.position = "none") + 
    geom_hline(yintercept = c(-tax_thresh,tax_thresh), lty=2, color="lightgrey") + 
    geom_vline(xintercept = c(-tax_thresh,tax_thresh), lty=2, color="lightgrey") + 
    ggrepel::geom_label_repel(data = . %>% filter(trait %in% c("g__Bacteroides","g__Akkermansia","g__Alistipes","g__Prevotella","g__Succinivibrio","g__Cryptobacteroides","g__Eubacterium_R","g__Methanobrevibacter_A","g__Coprococcus","g__SIG603","g__Senegalimassilia")), aes(label=trait, col=status), max.overlaps = 20, size=3) + 
    xlab("Pan vs. Human") + ylab("Human\nAFR vs. EUR") + scale_size_continuous(range=c(2,3)) 

plotset = data.frame(tax=c("g__Eubacterium_R","g__Methanobrevibacter_A","g__SIG603","g__Senegalimassilia", "g__Coprococcus", "g__Agathobacter", "g__Prevotella","g__Succinivibrio", "g__Bacteroides","g__Akkermansia"), group=rep(c("neutral","NHA","Human","Low HDI", "High HDI"), each=2),stringsAsFactors = F)


fig2_panel_b_neutral = gen[,plotset %>% filter(group=="neutral") %>% pull(tax), drop=F] %>% 
  rownames_to_column("sample")  %>% reshape2::melt() %>% left_join(sample_meta) %>% 
  mutate(host_group = case_when(grepl("HsA",host) ~ "Human_AFR", grepl("Hs",host) ~ "Human_EUR", TRUE ~ "NHA")) %>%
  left_join(colset %>% mutate(gid2=case_when(grepl("HsA",host) ~ 4, grepl("Hs", host) ~ 3, TRUE ~ 1)) %>% group_by(gid2) %>% mutate(shift = seq_along(host_long)/ifelse(grepl("Hs",host),4,6))) %>%
  left_join(plotset, by=c("variable"="tax")) %>% 
  ggplot(aes(y=value/10000)) + 
  geom_boxplot(aes(x=as.numeric(factor(host_group, levels=c("NHA","A","Human_EUR","Human_AFR")))-0.125, fill=host_group), width=.25, outlier.shape = NA) + 
  geom_jitter(width=.025, height=0, aes(x=gid2+shift, col=host_long)) + 
  theme(axis.text.x = element_text(angle=45, hjust=1)) + 
  scale_color_manual(values=colset$col, breaks=colset$host_long) + 
  scale_y_continuous(expand=c(.1,0)) + ylab("Abundance (%)") + 
  theme(legend.position = "none") + facet_wrap(~variable, scales="free_y") + 
  scale_fill_manual(values=c("lightblue3","darkblue","#FF8C00")) + scale_x_continuous(breaks=c(1,3,4), labels=c("NHA","Human (EUR)","Human (AFR)")) + xlab("") + 
  theme(strip.text.x = element_text(size = 10))

fig2_panel_b_nha = gen[,plotset %>% filter(group=="NHA") %>% pull(tax), drop=F] %>% 
  rownames_to_column("sample")  %>% reshape2::melt() %>% left_join(sample_meta) %>% 
  mutate(host_group = case_when(grepl("HsA",host) ~ "Human_AFR", grepl("Hs",host) ~ "Human_EUR", TRUE ~ "NHA")) %>%
  left_join(colset %>% mutate(gid2=case_when(grepl("HsA",host) ~ 4, grepl("Hs", host) ~ 3, TRUE ~ 1)) %>% group_by(gid2) %>% mutate(shift = seq_along(host_long)/ifelse(grepl("Hs",host),4,6))) %>%
  left_join(plotset, by=c("variable"="tax")) %>% 
  ggplot(aes(y=value/10000)) + 
  geom_boxplot(aes(x=as.numeric(factor(host_group, levels=c("NHA","A","Human_EUR","Human_AFR")))-0.125, fill=host_group), width=.25, outlier.shape = NA) + 
  geom_jitter(width=.025, height=0, aes(x=gid2+shift, col=host_long)) + 
  theme(axis.text.x = element_text(angle=45, hjust=1)) + 
  scale_color_manual(values=colset$col, breaks=colset$host_long) + 
  scale_y_continuous(expand=c(.1,0)) + ylab("Abundance (%)") + 
  theme(legend.position = "none") + facet_wrap(~variable, scales="free_y") + 
  scale_fill_manual(values=c("lightblue3","darkblue","#FF8C00")) + scale_x_continuous(breaks=c(1,3,4), labels=c("NHA","Human (EUR)","Human (AFR)")) + xlab("") + 
  theme(strip.text.x = element_text(size = 10))

fig2_panel_b_human = gen[,plotset %>% filter(group=="Human") %>% pull(tax), drop=F] %>% 
  rownames_to_column("sample")  %>% reshape2::melt() %>% left_join(sample_meta) %>% 
  mutate(host_group = case_when(grepl("HsA",host) ~ "Human_AFR", grepl("Hs",host) ~ "Human_EUR", TRUE ~ "NHA")) %>%
  left_join(colset %>% mutate(gid2=case_when(grepl("HsA",host) ~ 4, grepl("Hs", host) ~ 3, TRUE ~ 1)) %>% group_by(gid2) %>% mutate(shift = seq_along(host_long)/ifelse(grepl("Hs",host),4,6))) %>%
  left_join(plotset, by=c("variable"="tax")) %>% 
  ggplot(aes(y=value/10000)) + 
  geom_boxplot(aes(x=as.numeric(factor(host_group, levels=c("NHA","A","Human_EUR","Human_AFR")))-0.125, fill=host_group), width=.25, outlier.shape = NA) + 
  geom_jitter(width=.025, height=0, aes(x=gid2+shift, col=host_long)) + 
  theme(axis.text.x = element_text(angle=45, hjust=1)) + 
  scale_color_manual(values=colset$col, breaks=colset$host_long) + 
  scale_y_continuous(expand=c(.1,0)) + ylab("Abundance (%)") + 
  theme(legend.position = "none") + facet_wrap(~variable, scales="free_y") + 
  scale_fill_manual(values=c("lightblue3","darkblue","#FF8C00")) + scale_x_continuous(breaks=c(1,3,4), labels=c("NHA","Human (EUR)","Human (AFR)")) + xlab("") + 
  theme(strip.text.x = element_text(size = 10))

fig2_panel_b_hdilo = gen[,plotset %>% filter(group=="Low HDI") %>% pull(tax), drop=F] %>% 
  rownames_to_column("sample")  %>% reshape2::melt() %>% left_join(sample_meta) %>% 
  mutate(host_group = case_when(grepl("HsA",host) ~ "Human_AFR", grepl("Hs",host) ~ "Human_EUR", TRUE ~ "NHA")) %>%
  left_join(colset %>% mutate(gid2=case_when(grepl("HsA",host) ~ 4, grepl("Hs", host) ~ 3, TRUE ~ 1)) %>% group_by(gid2) %>% mutate(shift = seq_along(host_long)/ifelse(grepl("Hs",host),4,6))) %>%
  left_join(plotset, by=c("variable"="tax")) %>% 
  ggplot(aes(y=value/10000)) + 
  geom_boxplot(aes(x=as.numeric(factor(host_group, levels=c("NHA","A","Human_EUR","Human_AFR")))-0.125, fill=host_group), width=.25, outlier.shape = NA) + 
  geom_jitter(width=.025, height=0, aes(x=gid2+shift, col=host_long)) + 
  theme(axis.text.x = element_text(angle=45, hjust=1)) + 
  scale_color_manual(values=colset$col, breaks=colset$host_long) + 
  scale_y_continuous(expand=c(.1,0)) + ylab("Abundance (%)") + 
  theme(legend.position = "none") + facet_wrap(~variable, scales="free_y") + 
  scale_fill_manual(values=c("lightblue3","darkblue","#FF8C00")) + scale_x_continuous(breaks=c(1,3,4), labels=c("NHA","Human (EUR)","Human (AFR)")) + xlab("") + 
  theme(strip.text.x = element_text(size = 10)) 

fig2_panel_b_hdihi = gen[,plotset %>% filter(group=="High HDI") %>% pull(tax), drop=F] %>% 
  rownames_to_column("sample")  %>% reshape2::melt() %>% left_join(sample_meta) %>% 
  mutate(host_group = case_when(grepl("HsA",host) ~ "Human_AFR", grepl("Hs",host) ~ "Human_EUR", TRUE ~ "NHA")) %>%
  left_join(colset %>% mutate(gid2=case_when(grepl("HsA",host) ~ 4, grepl("Hs", host) ~ 3, TRUE ~ 1)) %>% group_by(gid2) %>% mutate(shift = seq_along(host_long)/ifelse(grepl("Hs",host),4,6))) %>%
  left_join(plotset, by=c("variable"="tax")) %>% 
  ggplot(aes(y=value/10000)) + 
  geom_boxplot(aes(x=as.numeric(factor(host_group, levels=c("NHA","A","Human_EUR","Human_AFR")))-0.125, fill=host_group), width=.25, outlier.shape = NA) + 
  geom_jitter(width=.025, height=0, aes(x=gid2+shift, col=host_long)) + 
  theme(axis.text.x = element_text(angle=45, hjust=1)) + 
  scale_color_manual(values=colset$col, breaks=colset$host_long) + 
  scale_y_continuous(expand=c(.1,0)) + ylab("Abundance (%)") + 
  theme(legend.position = "none") + facet_wrap(~variable, scales="free_y") + 
  scale_fill_manual(values=c("lightblue3","darkblue","#FF8C00")) + scale_x_continuous(breaks=c(1,3,4), labels=c("NHA","Human (EUR)","Human (AFR)")) + xlab("") + 
  theme(strip.text.x = element_text(size = 10)) 



fig2_panel_b = cowplot::plot_grid(cowplot::plot_grid(fig2_panel_b_neutral + theme(axis.text.x = element_blank(), axis.text.y = element_text(size=12), plot.margin=margin(t = 0,b=0, l=1, r=1)) + ylab(""),
                                                     ggplot(data=data.frame(x=1,y=1, label="unchanged"),aes(x=x,y=y,label=label)) + geom_text(col="darkgrey", size=4, angle=270) + theme_nothing(), rel_widths=c(.95,.05) ) ,
                                  NULL,
                                  cowplot::plot_grid(fig2_panel_b_nha + theme(axis.text.x = element_blank(), axis.text.y = element_text(size=12), plot.margin=margin(t = 0,b=0, l=1, r=1)) + ylab(""),
                                                     ggplot(data=data.frame(x=1,y=1, label="NHA"),aes(x=x,y=y,label=label)) + geom_text(col="#FF8C00", size=4, angle=270) + theme_nothing(), rel_widths=c(.95,.05) ) ,
                                  NULL,
                                  cowplot::plot_grid(fig2_panel_b_human + theme(axis.text.x = element_blank(), axis.text.y = element_text(size=12), plot.margin=margin(t = 0,b=0, l=1, r=1)), 
                                                     ggplot(data=data.frame(x=1,y=1, label="Human"),aes(x=x,y=y,label=label)) + geom_text(col="blue", size=4, angle=270) + theme_nothing(), rel_widths=c(.95,.05) ) ,
                                  NULL,
                                  cowplot::plot_grid(fig2_panel_b_hdihi + theme(axis.text.x = element_blank(), axis.text.y = element_text(size=12), plot.margin=margin(t = 0,b=0, l=1, r=1),plot.background = element_rect(fill='transparent')) + ylab(""),
                                                     ggplot(data=data.frame(x=1,y=1, label="Human (EUR)"),aes(x=x,y=y,label=label)) + geom_text(col="darkblue", size=4, angle=270) + theme_nothing(), rel_widths=c(.95,.05) ) ,
                                  NULL,
                                  cowplot::plot_grid(fig2_panel_b_hdilo + theme(plot.margin=margin(t = 0,b=0, l=1, r=1), axis.text = element_text(size=12)) + ylab(""), 
                                                     ggplot(data=data.frame(x=1,y=1, label="Human (AFR)                   "),aes(x=x,y=y,label=label)) + geom_text(col="lightblue3", size=4, angle=270) + theme_nothing(), rel_widths=c(.95,.05) ) ,
                                  ncol=1, rel_heights = c(.15,-.025,.15,-.025,.15,-.025,.15,-.025,.25), align="v")

fig2_panel_b
#####

fig2_panel_c = res_gen  %>% filter(comp=="human") %>% select(trait, mean_abu_nhp=mean_abu1) %>% left_join(res_gen %>% filter(comp=="hdi_diff") %>% select(trait, mean_abu_hsa=mean_abu1, mean_abu_hsg=mean_abu2,)) %>% mutate(status=case_when(trait %in% taxa_hihdi ~ "Human (EUR)", trait %in% taxa_lohdi ~ "Human (AFR)", trait %in% taxa_human ~ "Human",  trait %in% taxa_pan ~ "NHA", TRUE ~ "other")) %>% reshape2::melt(.) %>% 
  ggplot(aes(x=variable, y=value)) + 
  geom_line(aes(col=status, group=trait), size=0.2,alpha=.2) + 
  geom_line(data = . %>% group_by(status,variable) %>% summarize(value=mean(value)) %>% filter(status=="other"), aes(group=status, col=status), size=3) + 
  geom_line(data = . %>% group_by(status,variable) %>% summarize(value=mean(value)) %>% filter(status!="other"), aes(group=status, col=status), size=3) + 
  scale_x_discrete(expand = c(0,0), labels=c("NHA","Human (AFR)","Human (EUR)")) + 
  scale_y_continuous(breaks=c(0,5,10)) + 
  scale_color_manual(values=c("blue","lightblue3","darkblue","#FF8C00","grey")) + 
  xlab("") + ylab("Mean CLR Abu") + theme(axis.text.x = element_text(angle=45,hjust=1))


fig2c_new_data = gen %>% rownames_to_column("sample") %>% reshape2::melt(.) %>% left_join(sample_meta) %>% 
  mutate(status=case_when(variable %in% taxa_pan ~ "NHA", variable %in% taxa_hihdi ~ "Human (EUR)", variable %in% taxa_lohdi ~ "Human (AFR)", variable %in% taxa_human ~ "Human", TRUE ~ "other"))  %>% 
  mutate(host2=case_when(!grepl("Hs",host) ~ "NHA", grepl("HsA",host) ~ "Human (AFR)", !grepl("HsA",host) ~ "Human (EUR)")) %>%
  group_by(sample, host2, status) %>% summarise(cumsum = sum(value)) %>% filter(status!="other") %>% 
  left_join(data.frame(status=c("NHA","Human","Human (AFR)","Human (EUR)"), shift=c(-.25,-.125,.125,.25) ))  %>%
  left_join(data.frame(host2=c("NHA","Human (AFR)","Human (EUR)"), pos=c(1,3,2) )) %>% 
  mutate(pos_abs = pos + shift) %>% ungroup


fig2_panel_c = fig2c_new_data %>% ggplot(aes(x=pos_abs, y=cumsum/10000, fill=status, group=pos_abs))  + 
  geom_vline(xintercept = c(1.5,2.5), lty=2, color="lightgrey") + 
  scale_x_continuous(breaks=1:3, labels=c("NHA","Human (EUR)","Human (AFR)")) +
  geom_line(data = fig2c_new_data %>% 
              group_by(pos_abs, host2, status) %>% 
              summarise(cumsum=median(cumsum)), 
            aes(group=status, col=status, x=pos_abs), size=3, alpha=.75) +
  geom_boxplot(width=.1, aes(group=pos_abs, fill=status), outlier.shape = NA) +
  scale_color_manual(values=c("#fd8d3c","blue","lightblue3","darkblue"),breaks=c("NHA","Human","Human (AFR)","Human (EUR)")) +
  scale_fill_manual(values=c("#fd8d3c","blue","lightblue3","darkblue"),breaks=c("NHA","Human","Human (AFR)","Human (EUR)")) +
  ylab("Cumulative Abundance (%)") + xlab("Host")   # + 
  #geom_jitter(data = fig2c_new_data  %>% select(pos_abs, cumsum, status), aes(fill=status),shape=21)
  


### calculate enrichment between non-indus Humans and NHPs
aaa_ni = lapply(sample(taxa_lohdi, 39), function(xx) (gen %>% data.frame %>% rownames_to_column("sample") %>% melt(.) %>% filter(variable %in% xx) %>% left_join(sample_meta)  %>% filter(host_genus %in% c("Pan"), !host %in% c("HsG","HsD") ) %>% group_by(sample, host_genus) %>% summarize(cum_sum = sum(value)) %>% wilcox.test(.$cum_sum, mu=1000, data=., alternative="greater"))$p.value)
num_lohdi_in_nhp = sum((aaa_ni %>% unlist) < 0.05) 


aaa_hihdi = lapply(taxa_hihdi, function(xx) (gen %>% data.frame %>% rownames_to_column("sample") %>% melt(.) %>% filter(variable %in% xx) %>% left_join(sample_meta)  %>% filter(host_genus %in% c("Pan"), !host %in% c("HsG","HsD") ) %>% group_by(sample, host_genus) %>% summarize(cum_sum = sum(value)) %>% wilcox.test(.$cum_sum, mu=1000, data=., alternative="greater"))$p.value)

library(parallel)

aaa_rand_file = paste0(intermediatedata_folder, "random_share.Rds")

if(file.exists(aaa_rand_file)){
  aaa_rand=readRDS(aaa_rand_file)
}else{
  aaa_rand = lapply(1:999, function(f){print(f); aaa=lapply(sample(taxa_human, 39), function(xx) (
    gen %>% data.frame %>% rownames_to_column("sample") %>% melt(.) %>% 
      filter(variable %in% xx) %>% left_join(sample_meta) %>% filter(host_genus %in% c("Pan"), host!="HsG") %>% 
      group_by(sample, host_genus) %>% summarize(cum_sum = sum(value)) %>% 
      wilcox.test(.$cum_sum, mu=1000, data=., alternative="greater"))$p.value)
  return(sum((aaa %>% unlist) < 0.05))}) 
saveRDS(aaa_rand, aaa_rand_file)
}

p_enrich = 1-sum(unlist(aaa_rand) <= num_lohdi_in_nhp)/(999+1)

```

# Figure 2
## Composite Figure 1 d-i

```{r, fig.height=11.5, fig.width=10}

plot2 = cowplot::plot_grid(
  plot_grid(fig2_panel_a + theme(axis.text = element_text(size=12), axis.title = element_text(size=15)), 
            fig2_panel_c + theme(legend.position = "top", plot.margin = margin(b=0), legend.text = element_text(size=9), axis.title = element_text(size=15), axis.text = element_text(size=12)) + guides(color=guide_legend(title="", ncol=3), fill=guide_none()), ncol=1, align="v", labels=c("a","c")),
  NULL,
  fig2_panel_b, 
  ncol=3, rel_widths=c(0.45,.05,.5), labels=c("","b",""))

plot2

ggsave(filename = "figures_and_tables/Figure_2_new.png", plot2, height=8, width=10, bg="white")
```



## Abundance differences of functions

```{r}
###
func_abu_long = sgb_long %>% filter(value>0) %>% mutate(host_group=substr(host,1,1)) %>% select(sample, GreatApes_95_final=variable, host_group, value) %>% left_join(pangenome_all) %>% group_by(sample, ogs) %>% summarize(abundance=sum(value)) %>% filter(!is.na(ogs))
func_abu = reshape2::dcast(sample ~ ogs, value.var="abundance", fill=0, data=func_abu_long) %>% data.frame %>% column_to_rownames("sample")
# func_clr=compositions::clr(func_abu+1)
# func_clr[func_clr<0] = 0

#cand_func = func_clr %>% data.frame %>% rownames_to_column("sample") %>% reshape2::melt() %>% left_join(sample_meta)  %>% filter(host_genus != "Gorilla")  %>% group_by(host_long, variable) %>% summarise(mean_abu = mean(value), mean_prev = mean(value>0)) %>% filter(mean_prev > .2, mean_abu > 1) %>% pull(variable) %>% unique() %>% as.character()

### filter: Mean Prevalence > 20% and mean abundance > 1% (1000 cumulative TPM) within either Humans or Pan genus
cand_func = func_abu %>% data.frame %>% rownames_to_column("sample") %>% reshape2::melt() %>% left_join(sample_meta)  %>%
  filter(host_genus != "Gorilla")  %>% group_by(host_genus, variable) %>% 
  summarise(mean_abu = mean(value), mean_prev = mean(value>0)) %>% 
  filter(mean_prev > .2, mean_abu > 10000) %>% 
  pull(variable) %>% unique() %>% as.character()


### functional abundances are *not* clr-transformed as they are not compositional; 
### log-transformation of abundances is used instead
res_func_file = paste0(intermediatedata_folder, "res_func.Rds")

if(file.exists(res_func_file)){
res_func=readRDS(res_func_file) 
}else{
res_func = lapply(cand_func, function(cf){
  ab = func_abu %>% select(ab = !!cf) %>% mutate(ab=log(ab+1))
#  df = ab %>% reshape2::melt(.) %>% rownames_to_column("sample") %>% left_join(data.frame(func_clr)[,cf, drop=F] %>% rownames_to_column("sample") %>% select(sample, value_tpm=2)) %>% left_join(sample_meta)  %>% filter(host_genus != "Gorilla") %>% mutate(hdihi=host %in% c("HsG","HsD"), human= host %in% c("HsA1","HsG","HsA2","HsD"))
#  df_out=data.frame(trait=cf, comp=c("human","high_hdi"),summary(lm(value ~ human*hdihi, data = df))$coefficients[2:3,], bind_rows(df %>% group_by(human) %>% summarize(mean_abu=mean(value)) %>% select(mean_abu) %>% unlist(), df %>% filter(human) %>% group_by(indus) %>% summarize(mean_abu=mean(value)) %>% select(mean_abu) %>% unlist()), stringsAsFactors = F)
  df = ab %>% rownames_to_column("sample")  %>% reshape2::melt(.) %>% left_join(data.frame(func_abu)[,cf, drop=F] %>% rownames_to_column("sample") %>% select(sample, value_tpm=2)) %>% left_join(sample_meta) %>% filter(host_genus != "Gorilla") %>% mutate(hihdi=host %in% c("HsG","HsD"), human= host %in% c("HsA1","HsG","HsA2","HsD"))
  df_out=data.frame(trait=cf, comp=c("human","hdi_diff"),summary(lm(value ~ human*hihdi, data = df))$coefficients[2:3,], bind_rows(df %>% group_by(human) %>% summarize(mean_abu=mean(value_tpm)) %>% select(mean_abu) %>% unlist(), df %>% filter(human) %>% group_by(hihdi) %>% summarize(mean_abu=mean(value_tpm)) %>% select(mean_abu) %>% unlist()), stringsAsFactors = F)
  return(df_out)
}) %>% do.call("bind_rows",.) %>% mutate(log_fold_diff = log((mean_abu2+1)/(mean_abu1+1)))
saveRDS(res_func, res_func_file)
}

#res_func=res_func %>% mutate(trait=paste0("ko:",trait))

res_func$q <- p.adjust(res_func$Pr...t..,"bonferroni")
res_func_sub <- res_func %>% filter(trait %in% c(res_func %>% pull(trait))) %>% arrange(q) %>% left_join(KO_NAMES, by=c("trait"="ko"))

func_hihdi = res_func_sub %>% filter(comp=="hdi_diff", q<0.05, Estimate>0) %>% pull(trait)
func_lohdi = res_func_sub %>% filter(comp=="hdi_diff", q<0.05, Estimate<0) %>% pull(trait)
func_human = res_func_sub %>% filter(comp=="human", q<0.05, Estimate>0) %>% pull(trait)
func_chimp = res_func_sub %>% filter(comp=="human", q<0.05, Estimate<0) %>% pull(trait)
  
res_func = res_func %>% mutate(status=case_when( trait %in% func_chimp ~ "NHA",trait %in% func_hihdi ~ "Human_EUR", trait %in% func_lohdi ~ "Human_AFR", trait %in% func_human ~ "Human",  TRUE ~ "other")) 

write.table(res_func, "figures_and_tables/Suppl_Table_S6_Results_Func.tsv", row.names = F, sep="\t")

top_trait_func = res_func_sub %>% mutate(dir=sign(t.value)) %>% group_by(comp, dir) %>% slice_min(order_by=q, n=5) %>% pull(trait)

func_thresh = res_func %>% arrange(q) %>% filter(q<0.05) %>% tail(1) %>% pull(t.value) %>% abs
fig3_panel_a = res_func %>% reshape2::dcast(trait ~ comp, value.var="t.value") %>% left_join(res_func %>% filter(comp=="human") %>% select(trait, log_fold_diff, q, status)) %>% 
  ggplot(aes(x=human, y=hdi_diff)) + 
  geom_point(aes(col=status, size=abs(log_fold_diff)))  + 
  scale_color_manual(values=c("blue","lightblue3","darkblue","#FF8C00","grey")) + 
  theme(legend.position = "none") + 
  geom_hline(yintercept = c(-func_thresh,func_thresh), lty=2, color="lightgrey") + geom_vline(xintercept = c(-func_thresh,func_thresh), lty=2, color="lightgrey") + 
  ggrepel::geom_label_repel(data = . %>% filter(trait %in% top_trait_func), aes(label=trait), max.overlaps = 20, size=3) +  
  xlab("NHA vs. Human") + ylab("Human AFR vs. EUR") + scale_size_continuous(range=c(1,2)) 

#### enrichment of KOs in higher level annotations

res_func_mod2 = KO_TO_ALL %>% left_join(res_func, by=c("V1"="trait")) %>% mutate(q=ifelse(is.na(q),1,q )) %>% mutate(sig=q<0.05) 


res_func_mod_res2 = lapply(unique(res_func_mod2$V2), function(vv){
  print(vv)
  lapply(c("human","hdi_diff"), function(cc){
    dat=res_func_mod2 %>% filter(comp==cc | is.na(comp)) %>% mutate(this_mod = V2==vv) %>% arrange(-this_mod) %>% filter(!duplicated(V1)) 
    p= dat %>% select(sig, this_mod) %>% table %>% fisher.test(., alternative="greater")
    return(data.frame(mod=vv, comp=cc, n=sum(dat$this_mod), n_sig = nrow(dat %>% filter(this_mod, sig)), p=p$p.value, est=p$estimate, mean_sig_est=dat %>% filter(this_mod) %>% mutate(Estimate=ifelse(is.na(Estimate),0,Estimate)) %>% pull(Estimate) %>% mean))
    }) %>% do.call("bind_rows",.)
  }) %>% do.call("bind_rows",.)
  
res_func_mod_res2 = res_func_mod_res2 %>% filter(n>=5, n<=250) %>% mutate(q=p.adjust(p)) %>% left_join(ALL_NAMES, by=c("mod"="V1"))
  
res_func_mod_res2 %>% mutate(q=p.adjust(p)) %>% filter(q < 0.05, n>=5, n<=250) %>% left_join(ALL_NAMES, by=c("mod"="V1"))


virul = KO_TO_ALL %>% filter(V2 %in% c(res_func_mod_res2 %>% filter(comp=="human", q<0.05, mean_sig_est>0) %>% arrange(mean_sig_est) %>% filter(!grepl("M|map01053", mod)) %>% pull(mod))) %>% pull(V1) %>% unique() 

virul_sig = res_func %>% filter(trait %in% virul) %>% filter(comp=="human", q<0.05) %>% pull(trait) %>% gsub("ko:","",.)

 
#%>% select(sig, si,comp, V2) %>% table %>% data.frame() 
# 
# res_func_mod = res_func   %>% left_join(distinct(KO_TO_ALL), by=c("trait"="V1")) %>% filter(!is.na(V2)) %>% mutate(si=sign(t.value), sig=q<0.05) %>% select(sig, si,comp, V2) %>% table %>% data.frame() 
# 
# res_func_mod_res = res_func_mod  %>% group_by(comp, V2) %>% summarize(n=sum(Freq)) %>% filter(n>=5) %>% apply(., 1, function(x) (res_func %>% mutate(trait=gsub("[.]",":",trait)) %>% left_join(KO_NAMES, by=c("trait"="ko")) %>% left_join(distinct(KO_TO_ALL), by=c("trait"="V1")) %>% filter(!is.na(V2)) %>% filter(comp==x[1]) %>% mutate(this=V2==x[2], sig=q<0.05) %>% arrange(-sig,-this) %>% select(-annot) %>% distinct_at(.vars = "trait",.keep_all = T) %>% select(this, sig)  %>% mutate(this=factor(this, levels=c(TRUE,FALSE)), sig=factor(sig, levels=c(TRUE,FALSE)))  %>% table %>% fisher.test(., alternative="greater"))[c("p.value", "estimate")] %>% c(x, .)) %>% do.call("bind_rows",.) %>% mutate(q=p.adjust(p.value, "fdr")) %>%  left_join(ALL_NAMES, by=c("V2"="V1"))
# 
# res_func_mod_res = res_func_mod_res %>% left_join((res_func %>% left_join(distinct(KO_TO_ALL), by=c("trait"="V1")) %>% filter(!is.na(V2))) %>% group_by(comp, V2) %>% summarise(t_median = median(t.value))) %>% arrange(p.value)

write.table(res_func_mod_res2, "figures_and_tables/Suppl_Table_S7_Results_Modules.tsv", row.names = F, sep="\t")


panel_3b_data = res_func_mod_res2 %>% filter(q<0.05)  %>% select(comp, mod, description = V2) %>% 
  left_join(res_func %>% left_join(distinct(KO_TO_ALL), by=c("trait"="V1")) %>% filter(!is.na(V2)), by=c("comp","mod"="V2")) %>% 
  mutate(plotcat = case_when(q>0.05 ~ "E", comp=="hdi_diff" & t.value > 0 ~ "A", comp=="hdi_diff" & t.value < 0 ~ "B", comp=="human" & t.value > 0 ~ "C", comp=="human" & t.value < 0 ~ "D"), compcat = ifelse(comp=="human", "NHA vs.\nHuman", "Human\nAFR vs. EUR")) %>%
  (function(df) df %>% group_by(comp, mod) %>% summarise(t_median = median(t.value)) %>% left_join(df, .))




fig3_panel_b = panel_3b_data %>% 
  ggplot(aes(x=forcats::fct_reorder(mod, t.value, .fun = median), y=t.value, col=plotcat)) + 
  geom_jitter(width=.2, size=1) + 
  facet_grid( ~ compcat, scales = "free_x", space="free_x") + 
  theme(axis.text.x = element_text(angle=45, hjust=1)) + xlab("") + 
  geom_hline(yintercept = 0, lty=2, color="lightgrey") + 
  scale_color_manual(values=c("darkblue", "lightblue3", "blue","#FF8C00","grey"), breaks=c("A","B","C","D","E")) + 
  theme(legend.position = "none", strip.clip = "off") + ylab("t-Value") + 
  stat_summary(data= . %>% mutate(plotcat="F"), fun = median, fun.ymin = median, fun.ymax = median, geom = "crossbar", width = 0.5, col="black", alpha=.5)


```

## Enrichment in Indus. vs. non-indust. and human


```{r}
#####

cands= this_to_sgb %>% left_join(tax2) %>% 
  filter(host_group=="H", !is.na(genus)) %>% 
  mutate(trait=gsub("[-]",".",genus), status=case_when(trait %in% taxa_pan ~ "NHA", trait %in% taxa_hihdi ~ "Human_EUR", trait %in% taxa_lohdi ~ "Human_AFR", trait %in% taxa_human ~ "Human", TRUE ~ "other")) %>% 
  filter(status %in% c("Human_EUR","Human_AFR","Human")) %>% 
  select(GreatApes_95_final,status,genus, family) %>% 
  distinct %>% group_by(status, family) %>% 
  summarize(n=n()) %>% reshape2::dcast(family ~ status, value.var="n", fill=0)

### calculate pangenome KO differences between Blossum and non-Blossum taxa in Acidaminococcaceae, Bacteroidacea, Ruminococcaceae, Lachnospiracea, and Oscillospiraceae

cands_res = lapply(cands %>% mutate(notInd = Human + Human_AFR) %>% filter(Human_EUR > 10, notInd > 10) %>% pull(family),
                   function(tt){
                     print(tt);
                     tax_sub =  this_to_sgb %>% left_join(tax2) %>% filter(host_group=="H", !is.na(genus)) %>%
                       mutate(trait=gsub("[-]",".",genus), status=case_when(
                         trait %in% taxa_pan ~ "NHA",
                         trait %in% taxa_hihdi ~ "Human_EUR", 
                         trait %in% taxa_lohdi ~ "Human_AFR", 
                         trait %in% taxa_human ~ "Human",  
                         TRUE ~ "other")) %>% 
                       filter(status %in% c("Human_EUR","Human_AFR","Human"), family==tt) %>%
                       mutate(status=ifelse(status=="Human_EUR",status,"Human_AFR"),presence=1) %>%
                       reshape2::dcast(GreatApes_95_final+status ~ ogs, value.var="presence", fill=0)
                     tax_res=lapply(colnames(tax_sub %>% 
                                               select(-GreatApes_95_final, -status))[between(colMeans(tax_sub[,-1][,-1]),.1,.9)], 
                                    function(x) return(list(ogs=x, 
                                                            LO_prev=mean(tax_sub[tax_sub$status=="Human_AFR",x]),
                                                            HI_prev=mean(tax_sub[tax_sub$status=="Human_EUR",x]),
                                                            pval=fisher.test(table(tax_sub$status, tax_sub[,x]))$p.value))
                                    ) %>% do.call("bind_rows",.) %>% mutate(tax=tt)
                     tax_res %>% arrange(pval) %>% return()}) %>% 
  do.call("bind_rows",.) %>% 
  mutate(ogs=paste0("ko:",ogs)) %>% 
  mutate(effect=log2((HI_prev+0.01)/(LO_prev+0.01))) %>% 
  mutate(Zscore=-qnorm(pval/2)*sign(effect)) 

write.table(cands_res %>% select(ogs, tax, HI_prev, LO_prev, pval, effect, Zscore) %>% left_join(KO_NAMES, by=c("ogs"="ko")), "figures_and_tables/Suppl_Table_S8_Results_EUR_Family_Func.tsv", row.names = F, sep="\t")

### calculate meta analysis statistics for KOs across families

cands_meta = cands_res %>% 
  (function(df) df %>% left_join(df %>% group_by(ogs))) %>% 
  mutate(w=1, Z_w=Zscore*w) %>% group_by(ogs) %>% summarize(Z_sum = sum(Z_w), w_sum=sum(w^2), num_sig = sum(pval<0.05)) %>% 
  mutate(Z_meta=Z_sum/sqrt(w_sum), p_meta=2*pnorm(-abs(Z_meta))) %>% arrange(Z_meta)  %>% mutate(qval=ifelse(num_sig >= 2, p.adjust(p_meta),1)) %>% filter(w_sum>=3) %>% left_join(KO_NAMES, by=c("ogs"="ko")) 

write.table(cands_meta, "figures_and_tables/Suppl_Table_S9_Results_Human.EUR_Meta_Func.tsv", row.names = F, sep="\t")

#cand_mod = cands_meta %>% left_join(KO_TO_ALL, by=c("ogs"="V1")) %>% filter(!is.na(V2))%>% pull(V2) %>% unique()
cand_mod = KO_TO_ALL %>% group_by(V2) %>% summarize(n=n())

cand_mod_w_res = KO_TO_ALL %>% filter(V2 %in% (cand_mod %>% filter(n>=5, n<=250) %>% pull(V2))) %>% left_join(cands_meta, by=c("V1"="ogs")) %>% mutate(Zscore = ifelse(is.na(Z_meta),0, Z_meta), qval = ifelse(is.na(qval), 1, qval))

res_meta_mod_res_res = lapply(unique(cand_mod_w_res$V2), function(x) (cand_mod_w_res %>% mutate(this = V2==x, sig=qval<0.05) %>% arrange(-sig,-this)  %>% mutate(this=factor(this, levels=c(TRUE,FALSE)), sig=factor(sig, levels=c(TRUE,FALSE))) %>% distinct_at(.vars = "V1",.keep_all = T) %>% select(this, sig) %>% table %>% fisher.test(., alternative = "greater"))[c("p.value", "estimate")] %>% c(cat=x, .) ) 

res_meta_mod_res = res_meta_mod_res_res %>% do.call("bind_rows",.) %>% arrange(p.value) %>% left_join(ALL_NAMES, by=c("cat"="V1")) %>% mutate(q=p.adjust(p.value, "bonferroni")) %>% left_join(cand_mod, by=c("cat"="V2")) %>% select(group = cat, num_kos = n, p.value, q.value = q, group_name = V2)




#res_meta_mod_res = cands_meta %>% left_join(KO_TO_ALL, by=c("ogs"="V1")) %>% filter(!is.na(V2)) %>% group_by(V2) %>% summarize(n=n()) %>% filter(n>=5) %>% apply(., 1, function(x) (cands_meta %>% left_join(KO_TO_ALL, by=c("ogs"="V1")) %>% filter(!is.na(V2)) %>% mutate(this=V2==x[1], sig=ogs %in% (cands_meta %>% filter(qval<0.05) %>% pull(ogs))) %>% arrange(-sig,-this) %>% mutate(this=factor(this, levels=c(TRUE,FALSE)), sig=factor(sig, levels=c(TRUE,FALSE))) %>% distinct_at(.vars = "ogs",.keep_all = T) %>% select(this, sig) %>% table %>% fisher.test(., alternative = "greater"))[c("p.value", "estimate")] %>% c(cx, .)) %>% do.call("bind_rows",.) %>% arrange(p.value) %>% left_join(ALL_NAMES, by=c("V2"="V1")) %>% mutate(q=p.adjust(p.value, "fdr")) %>% select(group = V2, num_kos = n, p.value, q.value = q, group_name = V2.y)


panel_3c_data = res_meta_mod_res  %>% filter(q.value<0.05)  %>% select(group, group_name) %>% left_join(cands_meta %>% left_join(distinct(KO_TO_ALL), by=c("ogs"="V1")) %>% filter(!is.na(V2)), by=c("group"="V2")) %>% mutate(plotcat = case_when(qval>0.05 ~ "E", Z_meta > 0 ~ "A", Z_meta < 0 ~ "B"), compcat = "Human AFR vs. EUR", comp="hdi_diff")  %>% mutate(group = fct_reorder(group, Z_meta, .fun=median))

res_meta_mod_res = res_meta_mod_res %>% left_join(panel_3c_data %>% group_by(group) %>% summarize(Z_mean = mean(Z_meta)))

## 

write.table(res_meta_mod_res %>% select(group, group_name, num_kos, Z_mean, p.value, q.value), "figures_and_tables/Suppl_Table_S10_Results_Human.AFR_EUR_Meta_KEGG_enrich.tsv", row.names = F, sep="\t")
write.table(res_meta_mod_res %>% filter(q.value<0.05)  %>% select(group, group_name, num_kos, Z_mean, p.value, q.value), "figures_and_tables/Table_1_Results_Human.AFR_EUR_Meta_KEGG_enrich.tsv", row.names = F, sep="\t")

fig3_panel_c = panel_3c_data  %>% ggplot(aes(x=group, y=Z_meta, col=plotcat)) + geom_jitter(width=.2, size=1) + facet_grid( ~ compcat, scales = "free_x", space="free_x") + theme(axis.text.x = element_text(angle=45, hjust=1)) + xlab("") + geom_hline(yintercept = 0, lty=2, color="lightgrey") + scale_color_manual(values=c("darkblue","lightblue3","blue","#FF8C00","grey"), breaks=c("A","B","C","D","E")) + theme(legend.position = "none") + ylab("Z-Value") + stat_summary(fun = median, fun.ymin = median, fun.ymax = median, geom = "crossbar", width = 0.5, col="black", alpha=.5)



# K01712 = urocanate hydratase [EC:4.2.1.49]
# 4-Imidazolone-5-propanoate <=> Urocanate + H2O
# Make plot 

fig3_panel_d = cands_res %>% filter(ogs=="ko:K01712") %>% left_join(cands, by=c("tax"="family")) %>% select(LO_prev,HI_prev, tax) %>% reshape2::melt() %>% ggplot(aes(x=tax, y=value*100, fill=variable)) + geom_col(position = position_dodge2()) + geom_text(data = cands_res %>% filter(ogs=="ko:K01712") %>% mutate(value = .9, stars = case_when(pval < 0.001 ~ "***", pval < 0.01 ~ "**", pval < 0.05 ~ "*", T ~ "" )), aes(label=stars, fill="0")) + theme(legend.position = "none") + scale_fill_manual(values=c("white", "darkblue", "lightblue3")) + ylab("Prevalence (%)") + xlab("") + scale_y_continuous(limits=c(0,100))

plot3=cowplot::plot_grid(fig3_panel_a, 
                   cowplot::plot_grid(
                     fig3_panel_b + theme(axis.text = element_text(size=9), plot.margin = margin(b=-.5), axis.title = element_text(size=12)), 
                     cowplot::plot_grid(plotlist = cowplot::align_plots(
                       fig3_panel_c + theme(axis.text = element_text(size=9), axis.title = element_text(size=12)), 
                       fig3_panel_d + theme(axis.text.x = element_text(size=9, angle=45, hjust=1), axis.text.y = element_text(size=9), plot.margin = margin(t=-0.5), axis.title = element_text(size=12), plot.title = element_text(size=12)) + ggtitle("K01712 - urocanate hydratase"),
                       align="vh", axis = "btlr"
                       )
                    , labels=c("c","d")), ncol=1, labels=c("b",""))
                   , ncol=2, labels=c("a",""))


ggsave(filename = "figures_and_tables/Figure_3_new.png", plot3, height=5, width=12, bg="white")

```


## Source Data

```{r}
library("openxlsx")
# Write the first data set in a new workbook

wb=readRDS("SourceData_Figure1.Rds")

fig2a_ext = fig2_panel_a$data 
fig2b_ext = bind_rows(fig2_panel_b_neutral$data %>% select(sample, variable, host_long, value, group),
                      fig2_panel_b_nha$data %>% select(sample, variable, host_long, value, group),
                      fig2_panel_b_human$data %>% select(sample, variable, host_long, value, group),
                      fig2_panel_b_hdihi$data %>% select(sample, variable, host_long, value, group),
                      fig2_panel_b_hdilo$data %>% select(sample, variable, host_long, value, group)
                      ) %>% mutate(rel_abu = value / 10000) %>% select(-value)
fig2c_ext = fig2_panel_c$data %>% mutate(rel_abu = cumsum/10000) %>% select(sample, host2, status, rel_abu)


addWorksheet(wb, "Figure2a")
writeData(wb, sheet = "Figure2a", fig2a_ext)

addWorksheet(wb, "Figure2b")
writeData(wb, sheet = "Figure2b", fig2b_ext)

addWorksheet(wb, "Figure2c")
writeData(wb, sheet = "Figure2c", fig2c_ext)

####

fig3a_ext = fig3_panel_a$data
fig3b_ext = fig3_panel_b$data %>% select(compcat, pathway=mod, trait, t.value, q, status)
fig3c_ext = fig3_panel_c$data %>% select(compcat, pathway=group, trait=ogs, Z_meta, q=qval)

addWorksheet(wb, "Figure3a")
writeData(wb, sheet = "Figure3a", fig3a_ext)

addWorksheet(wb, "Figure3b")
writeData(wb, sheet = "Figure3b", fig3b_ext)

addWorksheet(wb, "Figure3c")
writeData(wb, sheet = "Figure3c", fig3c_ext)
saveRDS(wb, "SourceData_Figure123.Rds")


```