---
title: "Figure 1 Panels a,b,c; Figure S2"
author: "Malte Ruehlemann"
date: "`r Sys.Date()`"
output:
   BiocStyle::html_document:
      toc: true
      df_print: paged
      self_contained: true
      code_download: true
      highlight: tango
#bibliography: mylib.bib
editor_options:
  chunk_output_type: console
params:
  FIGPATH: "figures/"
---

<style type="text/css">
.main-container {
  max-width: 1800px;
  margin-left: auto;
  margin-right: auto;
}
</style>

```{r style}
# Set knit global options
library("knitr")
options(digits = 3, width = 80)
golden_ratio <- (1 + sqrt(5)) / 2
opts_chunk$set(echo = FALSE,
               tidy = FALSE,
               include = TRUE,
               fig.path = params$FIGPATH,
               dev='png',
               fig.height = 7.5,
               fig.width = 6 * golden_ratio,
               warning = F,
               message =F, 
               comment = '  ',
               dpi = 300,
               cache = FALSE)
library("rmarkdown")

# Pretty outputs
library("BiocStyle")
library("ggthemes") # add ggplot2 themes
library("ggplot2")
theme_set(theme_few(base_size = 18))

# Set seed for reproducibility
set.seed(222)
```

```{r}
#setwd("r_analysis_and_plots")
library(ggplot2)
library(tidyverse)
library(ape)
library(ggtree)
library(compositions)
library(phyloseq)
library(picante)
library(ggrepel)
library(reshape2)
library(cowplot)
library(plotly)
library(TreeDist)
library(phytools)
library(parallel)
library(ggpubr)

interactive=F

load("0_all_preprocessed.Robj")
```




## Abundance differences of genera

```{r}

colset=colset %>% arrange(host_long)
## clr transformation of genus level abundances
gen = gen[!rownames(gen) %in% sample_exclude,]
sgb_abundance = sgb_abundance[!rownames(sgb_abundance) %in% sample_exclude,]
sgb_long = sgb_long %>% filter(!sample %in% sample_exclude)

gen_clr = (gen+1) %>% data.frame %>% clr
gen_clr[gen_clr<0] = 0

### select candidate genera for testing with prevalence > 20% and mean abundance > 0.1% (1000 TPM) in one subgroup 
cand_gen = gen %>% data.frame %>% rownames_to_column("sample") %>% reshape2::melt() %>% left_join(sample_meta) %>% filter(host_genus != "Gorilla") %>% group_by(host_long, variable) %>% summarise(mean_abu = mean(value), mean_prev = mean(value>0)) %>% filter(mean_prev > .2, mean_abu>1000) %>% pull(variable) %>% unique() %>% as.character()

if(file.exists("../../../220303_Analysis_New/intermediate_data/res_gen.Rds")){
res_gen=readRDS("../../../220303_Analysis_New/intermediate_data/res_gen.Rds")
}else{
res_gen = do.call("rbind",lapply(cand_gen, function(cf){
  ab = gen_clr[,cf]
  df = ab %>% reshape2::melt(.) %>% rownames_to_column("sample") %>% left_join(data.frame(gen)[,cf, drop=F] %>% rownames_to_column("sample") %>% select(sample, value_tpm=2)) %>% left_join(sample_meta) %>% filter(host_genus != "Gorilla") %>% mutate(indus=host=="HsG", human= host %in% c("HsA1","HsG","HsA2"))
  df_out=data.frame(trait=cf, comp=c("human","indus"),summary(lm(value ~ human*indus, data = df))$coefficients[2:3,], bind_rows(df %>% group_by(human) %>% summarize(mean_abu=mean(value)) %>% select(mean_abu) %>% unlist(), df %>% filter(human) %>% group_by(indus) %>% summarize(mean_abu=mean(value)) %>% select(mean_abu) %>% unlist()), stringsAsFactors = F)
  return(df_out)
})) %>% do.call("bind_rows",.) %>% mutate(log_fold_diff = log((mean_abu2+0.01)/(mean_abu1+0.01)))
saveRDS(res_gen, "../../../220303_Analysis_New/intermediate_data/res_gen.Rds")
}

res_gen$q <- p.adjust(res_gen$Pr...t..,"bonferroni")
res_gen_sub <- res_gen %>% filter(trait %in% c(res_gen %>% filter(mean_abu1 > 1 | mean_abu2 > 1, q < 0.05) %>% pull(trait))) 

## assign taxa to group
taxa_indus = res_gen_sub %>% filter(comp=="indus", q<0.05, Estimate>0) %>% pull(trait)
taxa_nonindus = res_gen_sub %>% filter(comp=="indus", q<0.05, Estimate<0) %>% pull(trait)
taxa_human = res_gen_sub %>% filter(comp=="human", q<0.05, Estimate>0) %>% pull(trait)
taxa_chimp = res_gen_sub %>% filter(comp=="human", q<0.05, Estimate<0) %>% pull(trait)

res_gen = res_gen %>% mutate(status=case_when(trait %in% taxa_indus ~ "Human_Industrialized", trait %in% taxa_nonindus ~ "Human_Non-Indust.", trait %in% taxa_human ~ "Human",  trait %in% taxa_chimp ~ "NHP", TRUE ~ "other")) 

write.table(res_gen, "figures_and_tables/Suppl_Table_S4_Results_Tax.tsv", row.names = F, sep="\t")

####

top_trait_tax = res_gen %>% filter(q<0.05) %>% mutate(dir=sign(t.value)) %>% group_by(comp, dir) %>% slice_min(order_by=q, n=3) %>% pull(trait)
tax_thresh = res_gen %>% arrange(q) %>% filter(q<0.05) %>% tail(1) %>% pull(t.value) %>% abs

panel_d=res_gen %>% reshape2::dcast(trait ~ comp, value.var="t.value") %>% left_join(res_gen %>% filter(comp=="human") %>% select(trait, log_fold_diff, q)) %>%  left_join(sgb_reps %>% select(trait=genus, phylum2) %>% distinct()) %>% mutate(status=case_when(trait %in% taxa_indus ~ "Human_Industrialized", trait %in% taxa_nonindus ~ "Human_Non-Indust.", trait %in% taxa_human ~ "Human",  trait %in% taxa_chimp ~ "NHP", TRUE ~ "other")) %>% ggplot(aes(x=human, y=indus)) + geom_point(aes(col=status, size=abs(log_fold_diff)))  + scale_color_manual(values=c("blue","darkblue","#FF8C00","lightblue","grey")) + theme(legend.position = "none") + geom_hline(yintercept = c(-tax_thresh,tax_thresh), lty=2, color="lightgrey") + geom_vline(xintercept = c(-tax_thresh,tax_thresh), lty=2, color="lightgrey") + ggrepel::geom_label_repel(data = . %>% filter(trait %in% c("g__Bacteroides","g__Akkermansia","g__Alistipes","g__Prevotella","g__Succinivibrio","g__Cryptobacteroides","g__Methanobrevibacter_A","g__Coprococcus","g__SIG603","g__Senegalimassilia")), aes(label=trait, col=status), max.overlaps = 20, size=3) + xlab("NHP vs. Human") + ylab("Non-indus. vs. Indus.") + scale_size_continuous(range=c(2,3)) 

panel_e = gen[,c("g__SIG603","g__Coprococcus","g__Prevotella","g__Bacteroides"), drop=F] %>% rownames_to_column("sample")  %>% reshape2::melt() %>% left_join(sample_meta) %>% mutate(host_group = ifelse(grepl("^Hs", host),"Human","NHP")) %>% group_by(host_group) %>% mutate() %>% ggplot(aes(y=value/10000)) + geom_boxplot(aes(x=as.numeric(as.factor(host_group))-0.125, fill=host_group), width=.25, outlier.shape = NA) + geom_jitter(width=.025, height=0, aes(x=as.numeric(as.factor(host_group))+(gid/9), col=host_long)) + theme(axis.text.x = element_text(angle=45, hjust=1)) + scale_color_manual(values=colset$col, breaks=colset$host_long) + scale_y_continuous(expand=c(0,0)) + ylab("Abundance (%)") + theme(legend.position = "none") + facet_wrap(~variable, scales="free_y") + scale_fill_manual(values=c("blue","#FF8C00")) + scale_x_continuous(breaks=c(1,2), labels=c("Human","NHP")) + xlab("") + theme(strip.text.x = element_text(size = 10))


panel_f = res_gen  %>% filter(comp=="human") %>% select(trait, mean_abu_nhp=mean_abu1) %>% left_join(res_gen %>% filter(comp=="indus") %>% select(trait, mean_abu_hsa=mean_abu1, mean_abu_hsg=mean_abu2,)) %>% mutate(status=case_when(trait %in% taxa_indus ~ "Human_Industrialized", trait %in% taxa_nonindus ~ "Human_Non-Indust.", trait %in% taxa_human ~ "Human",  trait %in% taxa_chimp ~ "NHP", TRUE ~ "other")) %>% reshape2::melt(.) %>% ggplot(aes(x=variable, y=value)) + geom_line(aes(col=status, group=trait), size=0.2,alpha=.2) + geom_line(data = . %>% group_by(status,variable) %>% summarize(value=mean(value)),aes(group=status, col=status), size=3) + scale_x_discrete(expand = c(0,0), labels=c("NHP","Non-Indust.","Indust.")) + scale_y_continuous(breaks=c(0,5,10)) + scale_color_manual(values=c("blue","darkblue","lightblue","#FF8C00","grey")) + xlab("") + ylab("Mean CLR Abu") + theme(axis.text.x = element_text(angle=45,hjust=1))

### calculate enrichment between non-indus Humans and NHPs
aaa_ni = lapply(sample(taxa_nonindus, 30), function(xx) (gen %>% data.frame %>% rownames_to_column("sample") %>% melt(.) %>% filter(variable %in% xx) %>% left_join(sample_meta)  %>% filter(host_genus %in% c("Pan"), host!="HsG") %>% group_by(sample, host_genus) %>% summarize(cum_sum = sum(value)) %>% wilcox.test(.$cum_sum, mu=1000, data=., alternative="greater"))$p.value)
num_nonindus_in_nhp = sum((aaa_ni %>% unlist) < 0.05) 

library(parallel)
if(file.exists("../../../220303_Analysis_New/intermediate_data/random_share.Rds")){
aaa_rand=readRDS("../../../220303_Analysis_New/intermediate_data/random_share.Rds")
}else{
aaa_rand = lapply(1:999, function(f){print(f); aaa=lapply(sample(taxa_human, 30), function(xx) (gen %>% data.frame %>% rownames_to_column("sample") %>% melt(.) %>% filter(variable %in% xx) %>% left_join(sample_meta)  %>% filter(host_genus %in% c("Pan"), host!="HsG") %>% group_by(sample, host_genus) %>% summarize(cum_sum = sum(value)) %>% wilcox.test(.$cum_sum, mu=1000, data=., alternative="greater"))$p.value)
return(sum((aaa %>% unlist) < 0.05))}) 
saveRDS(aaa_rand, "../../../220303_Analysis_New/intermediate_data/random_share.Rds")
}

p_enrich = 1-sum(unlist(aaa_rand) <= num_nonindus_in_nhp)/(999+1)
```



## Abundance differences of functions

```{r}
###
func_abu_long = sgb_long %>% filter(value>0) %>% mutate(host_group=substr(host,1,1)) %>% select(sample, GreatApes_95_final=variable, host_group, value) %>% left_join(pangenome_all) %>% group_by(sample, ogs) %>% summarize(abundance=sum(value)) %>% filter(!is.na(ogs))
func_abu = reshape2::dcast(sample ~ ogs, value.var="abundance", fill=0, data=func_abu_long) %>% data.frame %>% column_to_rownames("sample")
func_clr=compositions::clr(func_abu+1)
func_clr[func_clr<0] = 0

cand_func = func_clr %>% data.frame %>% rownames_to_column("sample") %>% reshape2::melt() %>% left_join(sample_meta)  %>% filter(host_genus != "Gorilla")  %>% group_by(host_long, variable) %>% summarise(mean_abu = mean(value), mean_prev = mean(value>0)) %>% filter(mean_prev > .2, mean_abu > 1) %>% pull(variable) %>% unique() %>% as.character()

if(file.exists("../../../220303_Analysis_New/intermediate_data/res_func.Rds")){
res_func=readRDS("../../../220303_Analysis_New/intermediate_data/res_func.Rds") 
}else{
res_func = lapply(cand_func, function(cf){
  ab = func_clr[,cf]
  df = ab %>% reshape2::melt(.) %>% rownames_to_column("sample") %>% left_join(data.frame(func_clr)[,cf, drop=F] %>% rownames_to_column("sample") %>% select(sample, value_tpm=2)) %>% left_join(sample_meta)  %>% filter(host_genus != "Gorilla") %>% mutate(indus=host=="HsG", human= host %in% c("HsA1","HsG","HsA2"))
  df_out=data.frame(trait=cf, comp=c("human","indus"),summary(lm(value ~ human*indus, data = df))$coefficients[2:3,], bind_rows(df %>% group_by(human) %>% summarize(mean_abu=mean(value)) %>% select(mean_abu) %>% unlist(), df %>% filter(human) %>% group_by(indus) %>% summarize(mean_abu=mean(value)) %>% select(mean_abu) %>% unlist()), stringsAsFactors = F)
  return(df_out)
}) %>% do.call("bind_rows",.) %>% mutate(log_fold_diff = log((mean_abu2+0.01)/(mean_abu1+0.01)))
saveRDS(res_func, "../../../220303_Analysis_New/intermediate_data/res_func.Rds")
}

res_func=res_func %>% mutate(trait=paste0("ko:",trait))

res_func$q <- p.adjust(res_func$Pr...t..,"bonferroni")
res_func_sub <- res_func %>% filter(trait %in% c(res_func %>% filter(mean_abu1 > 1 | mean_abu2 > 1) %>% pull(trait))) %>% arrange(q) %>% left_join(KO_NAMES, by=c("trait"="ko"))

func_indus = res_func_sub %>% filter(comp=="indus", q<0.05, Estimate>0) %>% pull(trait)
func_nonindus = res_func_sub %>% filter(comp=="indus", q<0.05, Estimate<0) %>% pull(trait)
func_human = res_func_sub %>% filter(comp=="human", q<0.05, Estimate>0) %>% pull(trait)
func_chimp = res_func_sub %>% filter(comp=="human", q<0.05, Estimate<0) %>% pull(trait)
  
res_func = res_func %>% mutate(status=case_when(trait %in% func_indus ~ "Human_Industrialized", trait %in% func_nonindus ~ "Human_Non-Indust", trait %in% func_human ~ "Human",  trait %in% func_chimp ~ "NHP", TRUE ~ "other")) 

write.table(res_func, "figures_and_tables/Suppl_Table_S5_Results_Func.tsv", row.names = F, sep="\t")

top_trait_func = res_func_sub %>% mutate(dir=sign(t.value)) %>% group_by(comp, dir) %>% slice_min(order_by=q, n=5) %>% pull(trait)

func_thresh = res_func %>% arrange(q) %>% filter(q<0.05) %>% tail(1) %>% pull(t.value) %>% abs
panel_h = res_func %>% reshape2::dcast(trait ~ comp, value.var="t.value") %>% left_join(res_func %>% filter(comp=="human") %>% select(trait, log_fold_diff, q, status)) %>% 
  ggplot(aes(x=human, y=indus)) + 
  geom_point(aes(col=status, size=abs(log_fold_diff)))  + 
  scale_color_manual(values=c("blue","darkblue","#FF8C00","lightblue","grey")) + 
  theme(legend.position = "none") + 
  geom_hline(yintercept = c(-func_thresh,func_thresh), lty=2, color="lightgrey") + geom_vline(xintercept = c(-func_thresh,func_thresh), lty=2, color="lightgrey") + 
  ggrepel::geom_label_repel(data = . %>% filter(trait %in% top_trait_func), aes(label=trait), max.overlaps = 20, size=3) +  
  xlab("NHP vs. Human") + ylab("Non-indust. vs. Indus.") + scale_size_continuous(range=c(1,2)) 

#### enrichment of KOs in higher level annotations

res_func_mod = res_func   %>% left_join(distinct(KO_TO_ALL), by=c("trait"="V1")) %>% filter(!is.na(V2)) %>% mutate(si=sign(t.value), sig=q<0.05) %>% select(sig, si,comp, V2) %>% table %>% data.frame() 

res_func_mod_res = res_func_mod  %>% group_by(comp, V2) %>% summarize(n=sum(Freq)) %>% filter(n>=5) %>% apply(., 1, function(x) (res_func   %>% mutate(trait=gsub("[.]",":",trait)) %>% left_join(KO_NAMES, by=c("trait"="ko")) %>% left_join(distinct(KO_TO_ALL), by=c("trait"="V1")) %>% filter(!is.na(V2)) %>% filter(comp==x[1]) %>% mutate(this=V2==x[2], sig=q<0.05) %>% arrange(-sig,-this) %>% select(-annot) %>% distinct_at(.vars = "trait",.keep_all = T) %>% select(this, sig)  %>% mutate(this=factor(this, levels=c(TRUE,FALSE)), sig=factor(sig, levels=c(TRUE,FALSE)))  %>% table %>% fisher.test(., alternative="greater"))[c("p.value", "estimate")] %>% c(x, .)) %>% do.call("bind_rows",.) %>% mutate(q=p.adjust(p.value, "fdr")) %>%  left_join(ALL_NAMES, by=c("V2"="V1"))

write.table(res_func_mod_res, "figures_and_tables/Suppl_Table_S6_Results_Modules.tsv", row.names = F, sep="\t")

panel_i = res_func_mod_res %>% filter(q<0.05)  %>% select(comp, V2, V2.y) %>% left_join(res_func %>% left_join(distinct(KO_TO_ALL), by=c("trait"="V1")) %>% filter(!is.na(V2))) %>% mutate(plotcat = case_when(q>0.05 ~ "E", comp=="indus" & t.value > 0 ~ "A", comp=="indus" & t.value < 0 ~ "B", comp=="human" & t.value > 0 ~ "C", comp=="human" & t.value < 0 ~ "D"), compcat = ifelse(comp=="human", "NHP vs.\nHuman", "Non-Indust.\nvs. Indust.")) %>% ggplot(aes(x=V2, y=t.value, col=plotcat)) + geom_jitter(width=.2, size=1) + facet_grid( ~ compcat, scales = "free_x", space="free_x") + theme(axis.text.x = element_text(angle=45, hjust=1)) + xlab("") + geom_hline(yintercept = 0, lty=2, color="lightgrey") + scale_color_manual(values=c("darkblue", "lightblue", "blue","#FF8C00","grey"), breaks=c("A","B","C","D","E")) + theme(legend.position = "none", strip.clip = "off") + ylab("t-Value") + stat_summary(data= . %>% mutate(plotcat="F"), fun = median, fun.ymin = median, fun.ymax = median, geom = "crossbar", width = 0.5, col="black", alpha=.5)


```

## Enrichment in Indus. vs. non-indust. and human


```{r}
#####

cands= this_to_sgb %>% left_join(tax2) %>% filter(host_group=="H", !is.na(genus)) %>% mutate(trait=gsub("[-]",".",genus), status=case_when(trait %in% taxa_indus ~ "Human_Industrialized", trait %in% taxa_nonindus ~ "Human_Non.Indust.", trait %in% taxa_human ~ "Human",  trait %in% taxa_chimp ~ "NHP", TRUE ~ "other")) %>% filter(status %in% c("Human_Industrialized","Human_Non.Indust.","Human")) %>% select(GreatApes_95_final,status,genus, family) %>% distinct %>% group_by(status, family) %>% summarize(n=n()) %>% reshape2::dcast(family ~ status, value.var="n", fill=0)

### calculate pangenome KO differences between Blossum and non-Blossum taxa in Acidaminococcaceae, Bacteroidacea, Ruminococcaceae, Lachnospiracea, and Oscillospiraceae

cands_res = lapply(cands %>% mutate(notInd = Human + Human_Non.Indust.) %>% filter(Human_Industrialized > 10, notInd > 10) %>% pull(family), function(tt){print(tt); tax_sub =  this_to_sgb %>% left_join(tax2) %>% filter(host_group=="H", !is.na(genus)) %>% mutate(trait=gsub("[-]",".",genus), status=case_when(trait %in% taxa_indus ~ "Human_Industrialized", trait %in% taxa_nonindus ~ "Human_Non.Indust.", trait %in% taxa_human ~ "Human",  trait %in% taxa_chimp ~ "NHP", TRUE ~ "other")) %>% filter(status %in% c("Human_Industrialized","Human_Non.Indust.","Human"), family==tt) %>% mutate(status=ifelse(status=="Human_Industrialized",status,"Human_Non.Indust."),presence=1) %>% reshape2::dcast(GreatApes_95_final+status ~ ogs, value.var="presence", fill=0)
tax_res=lapply(colnames(tax_sub %>% select(-GreatApes_95_final, -status))[between(colMeans(tax_sub[,-1][,-1]),.1,.9)], function(x) return(list(ogs=x, V_prev=mean(tax_sub[tax_sub$status=="Human_Non.Indust.",x]), B_prev=mean(tax_sub[tax_sub$status=="Human_Industrialized",x]), pval=fisher.test(table(tax_sub$status, tax_sub[,x]))$p.value))) %>% do.call("bind_rows",.) %>% mutate(tax=tt)
tax_res %>% arrange(pval) %>% return()}) %>% do.call("bind_rows",.) %>% mutate(ogs=paste0("ko:",ogs)) %>% mutate(effect=log2((B_prev+0.01)/(V_prev+0.01))) %>% mutate(Zscore=-qnorm(pval/2)*sign(effect)) 

write.table(cands_res %>% select(ogs, tax, B_prev, V_prev, pval, effect, Zscore) %>% left_join(KO_NAMES, by=c("ogs"="ko")), "figures_and_tables/Suppl_Table_S7_Results_Indust_Family_Func.tsv", row.names = F, sep="\t")

### calculate meta analysis statistics for KOs across families

cands_meta = cands_res %>% 
  (function(df) df %>% left_join(df %>% group_by(ogs))) %>% 
  mutate(w=1, Z_w=Zscore*w) %>% group_by(ogs) %>% summarize(Z_sum = sum(Z_w), w_sum=sum(w^2), num_sig = sum(pval<0.05)) %>% 
  mutate(Z_meta=Z_sum/sqrt(w_sum), p_meta=2*pnorm(-abs(Z_meta))) %>% arrange(Z_meta)  %>% mutate(qval=ifelse(num_sig >= 2, p.adjust(p_meta),1)) %>% filter(w_sum>=3) %>% left_join(KO_NAMES, by=c("ogs"="ko")) 

write.table(cands_meta, "figures_and_tables/Suppl_Table_S8_Results_Human.Indust_Meta_Func.tsv", row.names = F, sep="\t")

#cand_mod = cands_meta %>% left_join(KO_TO_ALL, by=c("ogs"="V1")) %>% filter(!is.na(V2))%>% pull(V2) %>% unique()
cand_mod = KO_TO_ALL %>% group_by(V2) %>% summarize(n=n())

cand_mod_w_res = KO_TO_ALL %>% filter(V2 %in% (cand_mod %>% filter(n>=5, n<=250) %>% pull(V2))) %>% left_join(cands_meta, by=c("V1"="ogs")) %>% mutate(Zscore = ifelse(is.na(Z_meta),0, Z_meta), qval = ifelse(is.na(qval), 1, qval))

res_meta_mod_res_res = lapply(unique(cand_mod_w_res$V2), function(x) (cand_mod_w_res %>% mutate(this = V2==x, sig=qval<0.05) %>% arrange(-sig,-this)  %>% mutate(this=factor(this, levels=c(TRUE,FALSE)), sig=factor(sig, levels=c(TRUE,FALSE))) %>% distinct_at(.vars = "V1",.keep_all = T) %>% select(this, sig) %>% table %>% fisher.test(., alternative = "greater"))[c("p.value", "estimate")] %>% c(cat=x, .) ) 

res_meta_mod_res = res_meta_mod_res_res %>% do.call("bind_rows",.) %>% arrange(p.value) %>% left_join(ALL_NAMES, by=c("cat"="V1")) %>% mutate(q=p.adjust(p.value, "bonferroni")) %>% left_join(cand_mod, by=c("cat"="V2")) %>% select(group = cat, num_kos = n, p.value, q.value = q, group_name = V2)


#cand_mod


#res_meta_mod_res = cands_meta %>% left_join(KO_TO_ALL, by=c("ogs"="V1")) %>% filter(!is.na(V2)) %>% group_by(V2) %>% summarize(n=n()) %>% filter(n>=5) %>% apply(., 1, function(x) (cands_meta %>% left_join(KO_TO_ALL, by=c("ogs"="V1")) %>% filter(!is.na(V2)) %>% mutate(this=V2==x[1], sig=ogs %in% (cands_meta %>% filter(qval<0.05) %>% pull(ogs))) %>% arrange(-sig,-this) %>% mutate(this=factor(this, levels=c(TRUE,FALSE)), sig=factor(sig, levels=c(TRUE,FALSE))) %>% distinct_at(.vars = "ogs",.keep_all = T) %>% select(this, sig) %>% table %>% fisher.test(., alternative = "greater"))[c("p.value", "estimate")] %>% c(cx, .)) %>% do.call("bind_rows",.) %>% arrange(p.value) %>% left_join(ALL_NAMES, by=c("V2"="V1")) %>% mutate(q=p.adjust(p.value, "fdr")) %>% select(group = V2, num_kos = n, p.value, q.value = q, group_name = V2.y)


panel_g_data = res_meta_mod_res  %>% filter(q.value<0.05)  %>% select(group, group_name) %>% left_join(cands_meta %>% left_join(distinct(KO_TO_ALL), by=c("ogs"="V1")) %>% filter(!is.na(V2)), by=c("group"="V2")) %>% mutate(plotcat = case_when(qval>0.05 ~ "E", Z_meta > 0 ~ "A", Z_meta < 0 ~ "B"), compcat = "Indust vs.\nnon-Indust.", comp="indus")  %>% mutate(group = fct_reorder(group, Z_meta, .fun=median))

res_meta_mod_res = res_meta_mod_res %>% left_join(panel_g_data %>% group_by(group) %>% summarize(Z_mean = mean(Z_meta)))


write.table(res_meta_mod_res %>% select(group, group_name, num_kos, Z_mean, p.value, q.value), "figures_and_tables/Suppl_Table_S9_Results_Human.Indust_Meta_KEGG_enrich.tsv", row.names = F, sep="\t")
write.table(res_meta_mod_res %>% filter(q.value<0.05)  %>% select(group, group_name, num_kos, Z_mean, p.value, q.value), "figures_and_tables/Table_1_Results_Human.Indust_Meta_KEGG_enrich.tsv", row.names = F, sep="\t")

panel_g = panel_g_data  %>% ggplot(aes(x=group, y=Z_meta, col=plotcat)) + geom_jitter(width=.2, size=1) + facet_grid( ~ compcat, scales = "free_x", space="free_x") + theme(axis.text.x = element_text(angle=45, hjust=1)) + xlab("") + geom_hline(yintercept = 0, lty=2, color="lightgrey") + scale_color_manual(values=c("darkblue", "lightblue", "blue","#FF8C00","grey"), breaks=c("A","B","C","D","E")) + theme(legend.position = "none") + ylab("Z-Value") + stat_summary(fun = median, fun.ymin = median, fun.ymax = median, geom = "crossbar", width = 0.5, col="black", alpha=.5)



```

# Composite Figure 1 d-i

```{r, fig.height=11.5, fig.width=10}

plot1_right_top_aln = align_plots(panel_d  + theme(plot.margin = unit(c(1, 0, 0, 0), "cm")), panel_e, align = "h", axis = "tb")
plot1_right_top = cowplot::plot_grid(plot1_right_top_aln[[1]], plot1_right_top_aln[[2]], labels=c("d","e"))


plot1_right_mid = cowplot::plot_grid(
             get_legend(panel_f + guides(colour = guide_legend(ncol=1, title = ""))+ theme(legend.position = "bottom", legend.text = element_text(size=10), legend.justification = "top")),
             panel_f + theme(legend.position = "none"),
             panel_g + theme(plot.margin = unit(c(0, 1, 0, 1), "cm")),
ncol=3, labels=c("","f","g"), rel_widths = c(0.2,0.3,.5))


plot1_right_bottom = cowplot::plot_grid(panel_h, panel_i, labels=c("h","i") )


plot1_right = cowplot::plot_grid(plot1_right_top, plot1_right_mid, plot1_right_bottom, ncol=1, rel_heights = c(0.4,0.3,.3))

plot1_right

ggsave(filename = "figures_and_tables/fig1_right.png", plot1_right, height=11.5, width=10, bg="white")

plot1_left = readRDS("figures_and_tables/fig1_left.Rds")
plot1_complete = cowplot::plot_grid(plot1_left, plot1_right, rel_widths = c(.3,.7))

ggsave(filename = "figures_and_tables/Figure_1.png", plot1_complete, height=11.5, width=16.5, bg="white")

```